# Generated by Django 2.0.2 on 2018-03-28 20:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='boletin',
            fields=[
                ('bltn_id', models.AutoField(primary_key=True, serialize=False)),
                ('bltn_mes', models.CharField(max_length=2)),
                ('bltn_fechaPub', models.DateTimeField(verbose_name='Fecha publicacion Boletin')),
                ('bltn_archivo', models.FileField(upload_to='uploads/%Y/%m/%d')),
            ],
        ),
        migrations.CreateModel(
            name='envio',
            fields=[
                ('env_id', models.AutoField(primary_key=True, serialize=False)),
                ('env_subs_id', models.IntegerField()),
                ('env_bltn_id', models.IntegerField()),
                ('env_fechaEnvio', models.DateTimeField(verbose_name='Fecha envio Boletin')),
                ('env_estadoEnvio', models.BooleanField(default='false')),
            ],
        ),
        migrations.CreateModel(
            name='subscriptor',
            fields=[
                ('subs_id', models.AutoField(primary_key=True, serialize=False)),
                ('subs_nombre', models.CharField(max_length=50)),
                ('subs_apellido', models.CharField(max_length=50)),
                ('subs_mail', models.CharField(max_length=150)),
                ('subs_telefono', models.CharField(max_length=12)),
                ('subs_fecha', models.DateTimeField(verbose_name='Fecha de alta')),
                ('subs_medioPago', models.CharField(max_length=1)),
            ],
        ),
    ]
